default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: api
  password: Redbyte123

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
